import { useEffect, useState } from "react";
import api from "../../services/api";
import DepartmentCard from "../departments/DepartmentCard";
import { Link } from "react-router-dom";

function DepartmentsPreview() {
  const [departments, setDepartments] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState("");

        useEffect(() => {
            api
                  .get("/departments")
                        .then((response) => {
                                setDepartments(response.data.data);
                                        setLoading(false);
                                              })
                                                    .catch((error) => {
                                                            console.error(error);
                                                                    setError("Unable to load departments.");
                                                                            setLoading(false);
                                                                                  });
                                                                                    }, []);

                                                                                      if (loading) {
                                                                                          return (
                                                                                                <section className="section departments-preview">
                                                                                                        <div className="container">
                                                                                                                  <div className="section-heading">
                                                                                                                              <p className="section-subtitle">Academic Areas</p>
                                                                                                                                          <h2>Our Departments</h2>
                                                                                                                                                      <p>Loading departments...</p>
                                                                                                                                                                </div>
                                                                                                                                                                        </div>
                                                                                                                                                                              </section>
                                                                                                                                                                                  );
                                                                                                                                                                                    }

                                                                                                                                                                                      if (error) {
                                                                                                                                                                                          return (
                                                                                                                                                                                                <section className="section departments-preview">
                                                                                                                                                                                                        <div className="container">
                                                                                                                                                                                                                  <div className="section-heading">
                                                                                                                                                                                                                              <p className="section-subtitle">Academic Areas</p>
                                                                                                                                                                                                                                          <h2>Our Departments</h2>
                                                                                                                                                                                                                                                      <p className="error-message">{error}</p>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                          <section className="section departments-preview">
                                                                                                                                                                                                                                                                                                <div className="container">

                                                                                                                                                                                                                                                                                                        <div className="section-heading">
                                                                                                                                                                                                                                                                                                                  <p className="section-subtitle">Academic Areas</p>

                                                                                                                                                                                                                                                                                                                            <h2>Our Departments</h2>

                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                  Explore the departments and areas of study
                                                                                                                                                                                                                                                                                                                                                              available at AATPTC.
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                        {departments.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="empty-message">
                                                                                                                                                                                                                                                                                                                                                                                                              No departments available.
                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="departments-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {departments.slice(0, 3).map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <DepartmentCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    department={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="preview-action">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link to="/departments" className="btn-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View All Departments
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default DepartmentsPreview;
