import { useEffect, useState } from "react";
import api from "../../services/api";
import NewsCard from "../news/NewsCard";
import { Link } from "react-router-dom";

function LatestNews() {
  const [news, setNews] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState("");

        useEffect(() => {
            api
                  .get("/news")
                        .then((response) => {
                                setNews(response.data);
                                        setLoading(false);
                                              })
                                                    .catch((error) => {
                                                            console.error(error);
                                                                    setError("Unable to load news.");
                                                                            setLoading(false);
                                                                                  });
                                                                                    }, []);

                                                                                      if (loading) {
                                                                                          return (
                                                                                                <section className="section latest-news">
                                                                                                        <div className="container">
                                                                                                                  <div className="section-heading">
                                                                                                                              <p className="section-subtitle">Stay Updated</p>
                                                                                                                                          <h2>Latest News</h2>
                                                                                                                                                      <p>Loading news...</p>
                                                                                                                                                                </div>
                                                                                                                                                                        </div>
                                                                                                                                                                              </section>
                                                                                                                                                                                  );
                                                                                                                                                                                    }

                                                                                                                                                                                      if (error) {
                                                                                                                                                                                          return (
                                                                                                                                                                                                <section className="section latest-news">
                                                                                                                                                                                                        <div className="container">
                                                                                                                                                                                                                  <div className="section-heading">
                                                                                                                                                                                                                              <p className="section-subtitle">Stay Updated</p>
                                                                                                                                                                                                                                          <h2>Latest News</h2>
                                                                                                                                                                                                                                                      <p className="error-message">{error}</p>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                          <section className="section latest-news">
                                                                                                                                                                                                                                                                                                <div className="container">

                                                                                                                                                                                                                                                                                                        <div className="section-heading">
                                                                                                                                                                                                                                                                                                                  <p className="section-subtitle">Stay Updated</p>

                                                                                                                                                                                                                                                                                                                            <h2>Latest News</h2>

                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                  Get the latest news and updates from
                                                                                                                                                                                                                                                                                                                                                              Addis Ababa Tegbareid Polytechnic College.
                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                        {news.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                  <p className="empty-message">
                                                                                                                                                                                                                                                                                                                                                                                                              No news available.
                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="news-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      {news.slice(0, 3).map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <NewsCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    news={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="preview-action">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link to="/news" className="btn-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View All News
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default LatestNews;
