import { useEffect, useState } from "react";
import api from "../../services/api";
import ProgramCard from "../programs/ProgramCard";
import { Link } from "react-router-dom";

function ProgramsPreview() {
  const [programs, setPrograms] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState("");

        useEffect(() => {
            api
                  .get("/programs")
                        .then((response) => {
                                setPrograms(
                                          Array.isArray(response.data)
                                                      ? response.data
                                                                  : response.data.data
                                                                          );
                                                                                  setLoading(false);
                                                                                        })
                                                                                              .catch((error) => {
                                                                                                      console.error(error);
                                                                                                              setError("Unable to load programs.");
                                                                                                                      setLoading(false);
                                                                                                                            });
                                                                                                                              }, []);

                                                                                                                                if (loading) {
                                                                                                                                    return (
                                                                                                                                          <section className="section programs-preview">
                                                                                                                                                  <div className="container">
                                                                                                                                                            <div className="section-heading">
                                                                                                                                                                        <p className="section-subtitle">Academic Programs</p>
                                                                                                                                                                                    <h2>Our Programs</h2>
                                                                                                                                                                                                <p>Loading programs...</p>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                            );
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                if (error) {
                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                          <section className="section programs-preview">
                                                                                                                                                                                                                                                  <div className="container">
                                                                                                                                                                                                                                                            <div className="section-heading">
                                                                                                                                                                                                                                                                        <p className="section-subtitle">Academic Programs</p>
                                                                                                                                                                                                                                                                                    <h2>Our Programs</h2>
                                                                                                                                                                                                                                                                                                <p className="error-message">{error}</p>
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <section className="section programs-preview">
                                                                                                                                                                                                                                                                                                                                          <div className="container">

                                                                                                                                                                                                                                                                                                                                                  <div className="section-heading">
                                                                                                                                                                                                                                                                                                                                                            <p className="section-subtitle">
                                                                                                                                                                                                                                                                                                                                                                        Academic Programs
                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                            <h2>Our Programs</h2>

                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                  Discover programs designed to develop
                                                                                                                                                                                                                                                                                                                                                                                                                              practical and professional skills.
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {programs.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="empty-message">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              No programs available.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="programs-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {programs.slice(0, 3).map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ProgramCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    program={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="preview-action">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link to="/programs" className="btn-primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              View All Programs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default ProgramsPreview;
