import { useEffect, useState } from "react";
import api from "../services/api";
import AnnouncementCard from "../components/announcements/AnnouncementCard";

const Announcements = () => {
  const [announcements, setAnnouncements] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState("");

        useEffect(() => {
            const fetchAnnouncements = async () => {
                  try {
                          const response = await api.get("/announcements");

                                  setAnnouncements(response.data.data);
                                        } catch (err) {
                                                console.error(err);
                                                        setError("Failed to load announcements.");
                                                              } finally {
                                                                      setLoading(false);
                                                                            }
                                                                                };

                                                                                    fetchAnnouncements();
                                                                                      }, []);

                                                                                        if (loading) {
                                                                                            return (
                                                                                                  <section className="section announcements-page">
                                                                                                          <div className="container">
                                                                                                                    <div className="section-heading">
                                                                                                                                <p className="section-subtitle">Stay Informed</p>
                                                                                                                                            <h2>Announcements</h2>
                                                                                                                                                        <p>Loading announcements...</p>
                                                                                                                                                                  </div>
                                                                                                                                                                          </div>
                                                                                                                                                                                </section>
                                                                                                                                                                                    );
                                                                                                                                                                                      }

                                                                                                                                                                                        if (error) {
                                                                                                                                                                                            return (
                                                                                                                                                                                                  <section className="section announcements-page">
                                                                                                                                                                                                          <div className="container">
                                                                                                                                                                                                                    <div className="section-heading">
                                                                                                                                                                                                                                <p className="section-subtitle">Stay Informed</p>
                                                                                                                                                                                                                                            <h2>Announcements</h2>
                                                                                                                                                                                                                                                        <p className="error-message">{error}</p>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                            <section className="section announcements-page">
                                                                                                                                                                                                                                                                                                  <div className="container">

                                                                                                                                                                                                                                                                                                          <div className="section-heading">
                                                                                                                                                                                                                                                                                                                    <p className="section-subtitle">Stay Informed</p>

                                                                                                                                                                                                                                                                                                                              <h2>Announcements</h2>

                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                    Stay updated with important announcements and
                                                                                                                                                                                                                                                                                                                                                                information from AATPTC.
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                          {announcements.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                    <p className="empty-message">
                                                                                                                                                                                                                                                                                                                                                                                                                No announcements available.
                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="announcements-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {announcements.map((announcement) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AnnouncementCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={announcement.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      announcement={announcement}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Announcements;