import { useState } from "react";
import api from "../services/api";

const Contact = () => {
  const [formData, setFormData] = useState({
      full_name: "",
          email: "",
              phone: "",
                  subject: "",
                      message: "",
                        });

                          const [loading, setLoading] = useState(false);
                            const [success, setSuccess] = useState("");
                              const [error, setError] = useState("");

                                const handleChange = (e) => {
                                    const { name, value } = e.target;

                                        setFormData({
                                              ...formData,
                                                    [name]: value,
                                                        });
                                                          };

                                                            const handleSubmit = async (e) => {
                                                                e.preventDefault();

                                                                    setLoading(true);
                                                                        setSuccess("");
                                                                            setError("");

                                                                                try {
                                                                                      const response = await api.post("/contacts", formData);

                                                                                            setSuccess(response.data.message);

                                                                                                  setFormData({
                                                                                                          full_name: "",
                                                                                                                  email: "",
                                                                                                                          phone: "",
                                                                                                                                  subject: "",
                                                                                                                                          message: "",
                                                                                                                                                });
                                                                                                                                                    } catch (err) {
                                                                                                                                                          console.error(err);

                                                                                                                                                                setError(
                                                                                                                                                                        err.response?.data?.message ||
                                                                                                                                                                                "Failed to send your message."
                                                                                                                                                                                      );
                                                                                                                                                                                          } finally {
                                                                                                                                                                                                setLoading(false);
                                                                                                                                                                                                    }
                                                                                                                                                                                                      };

                                                                                                                                                                                                        return (
                                                                                                                                                                                                            <main>
                                                                                                                                                                                                                  <h1>Contact Us</h1>

                                                                                                                                                                                                                        <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                          <label htmlFor="full_name">Full Name</label>

                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                type="text"
                                                                                                                                                                                                                                                                            id="full_name"
                                                                                                                                                                                                                                                                                        name="full_name"
                                                                                                                                                                                                                                                                                                    value={formData.full_name}
                                                                                                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                <label htmlFor="email">Email</label>

                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                                                                                                                                                                                  id="email"
                                                                                                                                                                                                                                                                                                                                                                                                              name="email"
                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="phone">Phone</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="tel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        id="phone"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="phone"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={formData.phone}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label htmlFor="subject">Subject</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id="subject"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name="subject"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={formData.subject}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label htmlFor="message">Message</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={formData.message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rows="6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? "Sending..." : "Send Message"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {success && <p>{success}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && <p>{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default Contact;
