import { useEffect, useState } from "react";
import api from "../services/api";
import DownloadCard from "../components/downloads/DownloadCard";

const Downloads = () => {
  const [downloads, setDownloads] = useState([]);
    const [loading, setLoading] = useState(true);
      const [error, setError] = useState("");

        useEffect(() => {
            const fetchDownloads = async () => {
                  try {
                          const response = await api.get("/downloads");

                                  setDownloads(response.data.data);
                                        } catch (err) {
                                                console.error(err);
                                                        setError("Failed to load downloads.");
                                                              } finally {
                                                                      setLoading(false);
                                                                            }
                                                                                };

                                                                                    fetchDownloads();
                                                                                      }, []);

                                                                                        if (loading) {
                                                                                            return (
                                                                                                  <section className="section downloads-page">
                                                                                                          <div className="container">
                                                                                                                    <div className="section-heading">
                                                                                                                                <p className="section-subtitle">Resources</p>
                                                                                                                                            <h2>Downloads</h2>
                                                                                                                                                        <p>Loading downloads...</p>
                                                                                                                                                                  </div>
                                                                                                                                                                          </div>
                                                                                                                                                                                </section>
                                                                                                                                                                                    );
                                                                                                                                                                                      }

                                                                                                                                                                                        if (error) {
                                                                                                                                                                                            return (
                                                                                                                                                                                                  <section className="section downloads-page">
                                                                                                                                                                                                          <div className="container">
                                                                                                                                                                                                                    <div className="section-heading">
                                                                                                                                                                                                                                <p className="section-subtitle">Resources</p>
                                                                                                                                                                                                                                            <h2>Downloads</h2>
                                                                                                                                                                                                                                                        <p className="error-message">{error}</p>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                            <section className="section downloads-page">
                                                                                                                                                                                                                                                                                                  <div className="container">

                                                                                                                                                                                                                                                                                                          <div className="section-heading">
                                                                                                                                                                                                                                                                                                                    <p className="section-subtitle">Resources</p>

                                                                                                                                                                                                                                                                                                                              <h2>Downloads</h2>

                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                    Access useful documents and resources provided
                                                                                                                                                                                                                                                                                                                                                                by AATPTC.
                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                          {downloads.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                    <p className="empty-message">
                                                                                                                                                                                                                                                                                                                                                                                                                No downloads available.
                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="downloads-grid">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {downloads.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <DownloadCard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      item={item}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Downloads;