import { useEffect, useState } from "react";
import api from "../../services/api";

function DepartmentsManagement() {
  const [departments, setDepartments] = useState([]);
    const [loading, setLoading] = useState(true);

      const [name, setName] = useState("");
        const [slug, setSlug] = useState("");
          const [editingSlug, setEditingSlug] = useState(null);

            const fetchDepartments = async () => {
                try {
                      const response = await api.get("/departments");
                            setDepartments(response.data.data || response.data);
                                } catch (error) {
                                      console.error("Failed to load departments:", error);
                                          } finally {
                                                setLoading(false);
                                                    }
                                                      };

                                                        useEffect(() => {
                                                            fetchDepartments();
                                                              }, []);

                                                                const handleSubmit = async (e) => {
                                                                    e.preventDefault();

                                                                        try {
                                                                              if (editingSlug) {
                                                                                      await api.put(`/departments/${editingSlug}`, {
                                                                                                name,
                                                                                                          slug,
                                                                                                                  });
                                                                                                                        } else {
                                                                                                                                await api.post("/departments", {
                                                                                                                                          name,
                                                                                                                                                    slug,
                                                                                                                                                            });
                                                                                                                                                                  }

                                                                                                                                                                        setName("");
                                                                                                                                                                              setSlug("");
                                                                                                                                                                                    setEditingSlug(null);

                                                                                                                                                                                          await fetchDepartments();
                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                    console.error(
                                                                                                                                                                                                            "Failed to save department:",
                                                                                                                                                                                                                    error.response?.data || error
                                                                                                                                                                                                                          );
                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                  const handleEdit = (department) => {
                                                                                                                                                                                                                                      setEditingSlug(department.slug);
                                                                                                                                                                                                                                          setName(department.name);
                                                                                                                                                                                                                                              setSlug(department.slug);
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                  const handleDelete = async (slug) => {
                                                                                                                                                                                                                                                      if (!window.confirm("Are you sure you want to delete this department?")) {
                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                          await api.delete(`/departments/${slug}`);
                                                                                                                                                                                                                                                                                await fetchDepartments();
                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                          console.error(
                                                                                                                                                                                                                                                                                                  "Failed to delete department:",
                                                                                                                                                                                                                                                                                                          error.response?.data || error
                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                        if (loading) {
                                                                                                                                                                                                                                                                                                                            return <p>Loading departments...</p>;
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <div className="admin-departments">
                                                                                                                                                                                                                                                                                                                                          <h2>Departments Management</h2>

                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                  <label htmlFor="name">Department Name</label>

                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                        id="name"
                                                                                                                                                                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                value={name}
                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor="slug">Slug</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  id="slug"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={slug}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setSlug(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="computer-science"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {editingSlug ? "Update Department" : "Add Department"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {editingSlug && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setEditingSlug(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setName("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setSlug("");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {departments.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>No departments found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {departments.map((department) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={department.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3>{department.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Slug: {department.slug}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => handleEdit(department)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => handleDelete(department.slug)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default DepartmentsManagement;