import { useEffect, useState } from "react";
import api from "../../services/api";

function GalleryManagement() {
  const [gallery, setGallery] = useState([]);
    const [loading, setLoading] = useState(true);

      const [title, setTitle] = useState("");
        const [description, setDescription] = useState("");
          const [category, setCategory] = useState("");
            const [image, setImage] = useState(null);

              const [editingId, setEditingId] = useState(null);

                const fetchGallery = async () => {
                    try {
                          const response = await api.get("/gallery");

                                setGallery(response.data.data || response.data);
                                    } catch (error) {
                                          console.error(
                                                  "Failed to load gallery:",
                                                          error.response?.data || error
                                                                );
                                                                    } finally {
                                                                          setLoading(false);
                                                                              }
                                                                                };

                                                                                  useEffect(() => {
                                                                                      fetchGallery();
                                                                                        }, []);

                                                                                          const handleSubmit = async (e) => {
                                                                                              e.preventDefault();

                                                                                                  try {
                                                                                                        if (editingId) {
                                                                                                                await api.put(`/gallery/${editingId}`, {
                                                                                                                          title,
                                                                                                                                    description,
                                                                                                                                              image,
                                                                                                                                                        category
                                                                                                                                                                });
                                                                                                                                                                      } else {
                                                                                                                                                                              const formData = new FormData();

                                                                                                                                                                                      formData.append("title", title);
                                                                                                                                                                                              formData.append("description", description);
                                                                                                                                                                                                      formData.append("category", category);

                                                                                                                                                                                                              if (image) {
                                                                                                                                                                                                                        formData.append("image", image);
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                        await api.post("/gallery", formData);
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                    resetForm();
                                                                                                                                                                                                                                                          await fetchGallery();
                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                    console.error(
                                                                                                                                                                                                                                                                            "Failed to save gallery:",
                                                                                                                                                                                                                                                                                    error.response?.data || error
                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                  const handleEdit = (item) => {
                                                                                                                                                                                                                                                                                                      setEditingId(item.id);
                                                                                                                                                                                                                                                                                                          setTitle(item.title);
                                                                                                                                                                                                                                                                                                              setDescription(item.description || "");
                                                                                                                                                                                                                                                                                                                  setCategory(item.category || "");
                                                                                                                                                                                                                                                                                                                      setImage(item.image || "");
                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                          const handleDelete = async (id) => {
                                                                                                                                                                                                                                                                                                                              if (!window.confirm("Are you sure you want to delete this gallery item?")) {
                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                  await api.delete(`/gallery/${id}`);
                                                                                                                                                                                                                                                                                                                                                        await fetchGallery();
                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                          "Failed to delete gallery item:",
                                                                                                                                                                                                                                                                                                                                                                                  error.response?.data || error
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                const resetForm = () => {
                                                                                                                                                                                                                                                                                                                                                                                                    setEditingId(null);
                                                                                                                                                                                                                                                                                                                                                                                                        setTitle("");
                                                                                                                                                                                                                                                                                                                                                                                                            setDescription("");
                                                                                                                                                                                                                                                                                                                                                                                                                setCategory("");
                                                                                                                                                                                                                                                                                                                                                                                                                    setImage(null);
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                        if (loading) {
                                                                                                                                                                                                                                                                                                                                                                                                                            return <p>Loading gallery...</p>;
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="admin-gallery">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Gallery Management</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>Title</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Description</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      rows="5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setDescription(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>Category</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setCategory(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="">Select Category</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Campus">Campus</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="Laboratory">Laboratory</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="Workshop">Workshop</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Library">Library</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="Events">Events</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="Students">Students</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="Graduation">Graduation</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="Other">Other</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {!editingId && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label>Image</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setImage(e.target.files[0])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button type="submit">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {editingId ? "Update Gallery Item" : "Add Gallery Item"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {editingId && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button type="button" onClick={resetForm}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Gallery Items</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {gallery.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>No gallery items found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {gallery.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={item.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>{item.title}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Category: {item.category}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.description && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>{item.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.image && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Image: {item.image}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => handleEdit(item)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => handleDelete(item.id)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default GalleryManagement;