import { useEffect, useState } from "react";
import api from "../../services/api";

function NewsManagement() {
  const [news, setNews] = useState([]);
    const [loading, setLoading] = useState(true);

      const [title, setTitle] = useState("");
        const [slug, setSlug] = useState("");
          const [content, setContent] = useState("");
            const [image, setImage] = useState(null);

              const [editingSlug, setEditingSlug] = useState(null);

                const fetchNews = async () => {
                    try {
                          const response = await api.get("/news");

                                setNews(response.data.data || response.data);
                                    } catch (error) {
                                          console.error(
                                                  "Failed to load news:",
                                                          error.response?.data || error
                                                                );
                                                                    } finally {
                                                                          setLoading(false);
                                                                              }
                                                                                };

                                                                                  useEffect(() => {
                                                                                      fetchNews();
                                                                                        }, []);

                                                                                          const handleSubmit = async (e) => {
                                                                                              e.preventDefault();

                                                                                                  try {
                                                                                                        if (editingSlug) {
                                                                                                                await api.put(`/news/${editingSlug}`, {
                                                                                                                          title,
                                                                                                                                    slug,
                                                                                                                                              content,
                                                                                                                                                        image,
                                                                                                                                                                });
                                                                                                                                                                      } else {
                                                                                                                                                                              const formData = new FormData();

                                                                                                                                                                                      formData.append("title", title);
                                                                                                                                                                                              formData.append("slug", slug);
                                                                                                                                                                                                      formData.append("content", content);

                                                                                                                                                                                                              if (image) {
                                                                                                                                                                                                                        formData.append("image", image);
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                        await api.post("/news", formData);
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                    resetForm();
                                                                                                                                                                                                                                                          await fetchNews();
                                                                                                                                                                                                                                                              } catch (error) {
                                                                                                                                                                                                                                                                    console.error(
                                                                                                                                                                                                                                                                            "Failed to save news:",
                                                                                                                                                                                                                                                                                    error.response?.data || error
                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                  const handleEdit = (article) => {
                                                                                                                                                                                                                                                                                                      setEditingSlug(article.slug);
                                                                                                                                                                                                                                                                                                          setTitle(article.title);
                                                                                                                                                                                                                                                                                                              setSlug(article.slug);
                                                                                                                                                                                                                                                                                                                  setContent(article.content || "");
                                                                                                                                                                                                                                                                                                                      setImage(article.image || null);
                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                          const handleDelete = async (slug) => {
                                                                                                                                                                                                                                                                                                                              if (!window.confirm("Are you sure you want to delete this news article?")) {
                                                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                  await api.delete(`/news/${slug}`);
                                                                                                                                                                                                                                                                                                                                                        await fetchNews();
                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                  console.error(
                                                                                                                                                                                                                                                                                                                                                                          "Failed to delete news:",
                                                                                                                                                                                                                                                                                                                                                                                  error.response?.data || error
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                const resetForm = () => {
                                                                                                                                                                                                                                                                                                                                                                                                    setEditingSlug(null);
                                                                                                                                                                                                                                                                                                                                                                                                        setTitle("");
                                                                                                                                                                                                                                                                                                                                                                                                            setSlug("");
                                                                                                                                                                                                                                                                                                                                                                                                                setContent("");
                                                                                                                                                                                                                                                                                                                                                                                                                    setImage(null);
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                        if (loading) {
                                                                                                                                                                                                                                                                                                                                                                                                                            return <p>Loading news...</p>;
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="admin-news">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>News Management</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <form onSubmit={handleSubmit}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label>Title</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(e) => setTitle(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Slug</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={slug}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setSlug(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="college-announcement"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={!!editingSlug}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <label>Content</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rows="8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={content}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setContent(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {!editingSlug && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label>Image</label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setImage(e.target.files[0])}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {editingSlug ? "Update News" : "Add News"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {editingSlug && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="button" onClick={resetForm}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Cancel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <hr />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>Existing News</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {news.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>No news articles found.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {news.map((article) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={article.id}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3>{article.title}</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Slug: {article.slug}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {article.content?.substring(0, 150)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {article.content?.length > 150 ? "..." : ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {article.image && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Image: {article.image}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => handleEdit(article)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Edit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => handleDelete(article.slug)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default NewsManagement;