const Department = require("../models/departmentModel");

const getDepartments = (req, res) => {
  Department.getAllDepartments((err, results) => {
      if (err) {
            return res.status(500).json({
                    success: false,
                            message: err.message,
                                  });
                                      }

                                          res.json({
                                                success: true,
                                                      count: results.length,
                                                            data: results,
                                                                });
                                                                  });
                                                                  };


                                                                  const getDepartment = (req, res) => {
                                                                          const { slug } = req.params;

                                                                            Department.getDepartmentBySlug(slug, (err, results) => {
                                                                                if (err) {
                                                                                      return res.status(500).json({
                                                                                              success: false,
                                                                                                      message: err.message,
                                                                                                            });
                                                                                                                }

                                                                                                                    if (results.length === 0) {
                                                                                                                          return res.status(404).json({
                                                                                                                                  success: false,
                                                                                                                                          message: "Department not found",
                                                                                                                                                });
                                                                                                                                                    }

                                                                                                                                                        res.json({
                                                                                                                                                              success: true,
                                                                                                                                                                    data: results[0],
                                                                                                                                                                        });
                                                                                                                                                                          });
                                                                                                                                                                          };
                                                                  

                                                                                                                                                                          const createDepartment = (req, res) => {
                                                                                                                                                                            console.log(req.admin)
                                                                                                                                                                              const { name, slug } = req.body;

                                                                                                                                                                              if (!name || !slug) {
                                                                                                                                                                                return res.status(400).json({
                                                                                                                                                                                    success: false,
                                                                                                                                                                                        message: "Name and slug are required.",
                                                                                                                                                                                          });
                                                                                                                                                                                          }
                                                                                                                                                                                Department.createDepartment(req.body, (err, result) => {
                                                                                                                                                                                    if (err) {
                                                                                                                                                                                          return res.status(500).json({
                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                          message: err.message,
                                                                                                                                                                                                                });
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        res.status(201).json({
                                                                                                                                                                                                                              success: true,
                                                                                                                                                                                                                                    message: "Department created successfully",
                                                                                                                                                                                                                                          id: result.insertId,
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                };
                                                                             
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                const updateDepartment = (req, res) => {
                                                                                                                                                                                                                                                        const { slug } = req.params;

                                                                                                                                                                                                                                                          Department.updateDepartment(slug, req.body, (err, result) => {
                                                                                                                                                                                                                                                              if (err) {
                                                                                                                                                                                                                                                                    return res.status(500).json({
                                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                                    message: err.message,
                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                  if (result.affectedRows === 0) {
                                                                                                                                                                                                                                                                                                        return res.status(404).json({
                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                        message: "Department not found",
                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                      res.json({
                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                  message: "Department updated successfully",
                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                        };
                                                                                 
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        const deleteDepartment = (req, res) => {
                                                                                                                                                                                                                                                                                                                                                              const { slug } = req.params;

                                                                                                                                                                                                                                                                                                                                                                Department.deleteDepartment(slug, (err, result) => {
                                                                                                                                                                                                                                                                                                                                                                    if (err) {
                                                                                                                                                                                                                                                                                                                                                                          return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                                                                                                                                                                                                          message: err.message,
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                        if (result.affectedRows === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                              return res.status(404).json({
                                                                                                                                                                                                                                                                                                                                                                                                                      success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                              message: "Department not found",
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                  success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        message: "Department deleted successfully",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                        
                                                                  module.exports = {
                                                                    getDepartments, getDepartment, createDepartment, updateDepartment, deleteDepartment
                                                                    };