
const gallery = require("../models/galleryModel");

const getGalleries = (req, res) => {
  gallery.getAllGalleries((err, results) => {
      if (err) {
            return res.status(500).json({
                    success: false,
                            message: err.message,
                                  });
                                      }

                                          res.json({
                                                success: true,
                                                      count: results.length,
                                                            data: results,
                                                                });
                                                                  });
                                                                  };

                                                                  const getSingleGallery = (req, res) => {
                                                                    const { id } = req.params;

                                                                      gallery.getGalleryById(id, (err, results) => {
                                                                          if (err) {
                                                                                return res.status(500).json({
                                                                                        success: false,
                                                                                                message: err.message,
                                                                                                      });
                                                                                                          }

                                                                                                              if (results.length === 0) {
                                                                                                                    return res.status(404).json({
                                                                                                                            success: false,
                                                                                                                                    message: "gallery not found",
                                                                                                                                          });
                                                                                                                                              }

                                                                                                                                                  res.json({
                                                                                                                                                        success: true,
                                                                                                                                                              data: results[0],
                                                                                                                                                                  });
                                                                                                                                                                    });
                                                                                                                                                                    };

                                                                                                                                                                    const createGallery = (req, res) => {
                                                                                                                                                                        const galleryData = {
                                                                                                                                                                                  ...req.body,
                                                                                                                                                                                      image: req.file ? req.file.filename : null,
                                                                                                                                                                                        };
                                                                                                                                                                        
                                                                                                                                                                      gallery.createGallery(galleryData, (err, result) => {
                                                                                                                                                                          if (err) {
                                                                                                                                                                                return res.status(500).json({
                                                                                                                                                                                        success: false,
                                                                                                                                                                                                message: err.message,
                                                                                                                                                                                                      });
                                                                                                                                                                                                          }

                                                                                                                                                                                                              res.status(201).json({
                                                                                                                                                                                                                    success: true,
                                                                                                                                                                                                                          message: "gallery created successfully",
                                                                                                                                                                                                                                id: result.insertId,
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                      const updateGallery = (req, res) => {
                                                                                                                                                                                                                                        const { id } = req.params;

                                                                                                                                                                                                                                          gallery.updateGallery(id, req.body, (err, result) => {
                                                                                                                                                                                                                                              if (err) {
                                                                                                                                                                                                                                                    return res.status(500).json({
                                                                                                                                                                                                                                                            success: false,
                                                                                                                                                                                                                                                                    message: err.message,
                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                  if (result.affectedRows === 0) {
                                                                                                                                                                                                                                                                                        return res.status(404).json({
                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                        message: "gallery not found",
                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                      res.json({
                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                  message: "gallery updated successfully",
                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                        const deleteGallery = (req, res) => {
                                                                                                                                                                                                                                                                                                                                          const { id } = req.params;

                                                                                                                                                                                                                                                                                                                                            gallery.deleteGallery(id, (err, result) => {
                                                                                                                                                                                                                                                                                                                                                if (err) {
                                                                                                                                                                                                                                                                                                                                                      return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                              success: false,
                                                                                                                                                                                                                                                                                                                                                                      message: err.message,
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                    if (result.affectedRows === 0) {
                                                                                                                                                                                                                                                                                                                                                                                          return res.status(404).json({
                                                                                                                                                                                                                                                                                                                                                                                                  success: false,
                                                                                                                                                                                                                                                                                                                                                                                                          message: "gallery not found",
                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                              success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                    message: "gallery deleted successfully",
                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                          module.exports = {
                                                                                                                                                                                                                                                                                                                                                                                                                                            getGalleries,
                                                                                                                                                                                                                                                                                                                                                                                                                                              getSingleGallery,
                                                                                                                                                                                                                                                                                                                                                                                                                                                createGallery,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  updateGallery,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    deleteGallery,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    };